version: "3.8"

services:
  build:
    image: tinier-world-app
    build:
      context: .
      dockerfile: Dockerfile

  app:
    image: tinier-world-app
    # restart: always
    ports:
      - 8080:7777
    volumes:
      - .:/src
    depends_on:
      - build

  faiss_server:
    #build: .
    image: tinier-world-app
    command: uvicorn workers.get_items_from_faiss:app --host 0.0.0.0 --port 6666
    ports:
      - 8081:6666
    volumes:
      - .:/src
    depends_on:
      - build

  worker:
    #build: .
    image: tinier-world-app
    # restart: always
    command: python -u workers/kafka_to_pg_logs.py
    depends_on:
      - app
    ports:
      - 9965:9965
    volumes:
      - .:/src
